// Run with PLAYWRIGHT_MODULE pointing to the installed Playwright package, if not in node_modules.
const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const artifacts=path.join(__dirname,'artifacts');
const url=process.env.TEST_URL||'http://127.0.0.1:8768';
(async()=>{
await fs.mkdir(artifacts,{recursive:true});
const browser=await chromium.launch({headless:true,channel:process.env.TEST_BROWSER_CHANNEL||'msedge'});
const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});
const p=await context.newPage(),errors=[];global.debugPage=p;p.on('pageerror',e=>errors.push(e.message));
await p.goto(url);await p.getByRole('heading',{name:'Оборудование',exact:true}).waitFor();
await p.getByRole('button',{name:'Добавить оборудование',exact:true}).first().click();
await p.getByLabel('Название',{exact:true}).fill('Sony FX3');await p.getByLabel('Инвентарный номер',{exact:true}).fill('CAM-001');await p.locator('dialog').getByLabel('Категория',{exact:true}).fill('Камеры');await p.getByLabel('Состояние',{exact:true}).fill('Отличное');
for(const [i,rate]of [4500,4000,3500,3000].entries())await p.locator(`[name=rate${i}]`).fill(String(rate));
await p.getByRole('button',{name:'Сохранить',exact:true}).click();await p.locator('dialog').waitFor({state:'hidden'});
await p.locator('#mobile-nav').getByRole('link',{name:'Клиенты',exact:true}).click();await p.getByRole('button',{name:'Добавить клиента',exact:true}).first().click();
await p.getByLabel('Имя / название компании').fill('ООО Кадр');await p.getByLabel('Телефон',{exact:true}).fill('+7 999 123-45-67');await p.getByRole('button',{name:'Сохранить',exact:true}).click();await p.locator('dialog').waitFor({state:'hidden'});
await p.locator('#mobile-nav').getByRole('link',{name:'Оборудование',exact:true}).click();await p.getByRole('button',{name:'Сдать в аренду'}).click();
await p.getByLabel('Дата выдачи').fill('2026-09-22');await p.locator('dialog').getByLabel('Срок аренды').selectOption('open');await p.getByRole('button',{name:'Выдать оборудование'}).click();await p.locator('dialog').waitFor({state:'hidden'});
let db=await p.evaluate(()=>JSON.parse(localStorage.getItem('rental-equipment.db')));assert.equal(db.rentals.length,1);assert.equal(db.rentals[0].due,null);
await p.reload();await p.getByRole('button',{name:'Принять возврат'}).waitFor();assert.equal(await p.getByRole('button',{name:'Удалить',exact:true}).isDisabled(),true);
await p.getByRole('button',{name:'Принять возврат'}).click();await p.getByLabel('Дата возврата').fill('2026-10-02');await p.getByLabel('Оплачено полностью').check();assert.match(await p.locator('#return-quote').innerText(),/40.*000/);await p.getByRole('button',{name:'Подтвердить возврат'}).click();await p.locator('dialog').waitFor({state:'hidden'});
db=await p.evaluate(()=>JSON.parse(localStorage.getItem('rental-equipment.db')));assert.equal(db.rentals[0].total,40000);assert.equal(db.rentals[0].paid,40000);assert.equal(db.rentals[0].status,'closed');
await p.locator('#mobile-nav').getByRole('link',{name:'Цены',exact:true}).click();await p.getByRole('button',{name:'Изменить тарифы'}).click();await p.locator('[name=rate0]').fill('5000');await p.getByRole('button',{name:'Сохранить',exact:true}).click();await p.locator('dialog').waitFor({state:'hidden'});
await p.locator('#mobile-nav').getByRole('link',{name:'История',exact:true}).click();const downloadPromise=p.waitForEvent('download');await p.getByRole('button',{name:'CSV',exact:true}).click();const csvDownload=await downloadPromise;const buffer=await fs.readFile(await csvDownload.path());assert.deepEqual([...buffer.subarray(0,3)],[239,187,191]);assert.ok(buffer.toString().includes('Возврат'));
await p.getByRole('button',{name:'Очистить историю'}).click();await p.locator('#confirm-delete').click();await p.locator('dialog').waitFor({state:'hidden'});db=await p.evaluate(()=>JSON.parse(localStorage.getItem('rental-equipment.db')));assert.equal(db.history.length,0);assert.equal(db.rentals[0].total,40000);
await p.getByRole('button',{name:'Настройки и резервная копия'}).click();const backupPromise=p.waitForEvent('download');await p.getByRole('button',{name:'Скачать полную копию JSON'}).click();const backup=await backupPromise;const backupBuffer=await fs.readFile(await backup.path());await p.getByRole('button',{name:'Восстановить из JSON'}).click();await p.locator('[name=backup]').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:backupBuffer});await p.getByLabel('Подтверждаю замену базы на этом устройстве').check();await p.getByRole('button',{name:'Восстановить',exact:true}).click();await p.locator('dialog').waitFor({state:'hidden'});
await p.locator('#mobile-nav').getByRole('link',{name:'Оборудование',exact:true}).click();await p.getByRole('heading',{name:'Оборудование',exact:true}).waitFor();await p.getByRole('searchbox',{name:'Поиск'}).fill('not found');await p.getByRole('heading',{name:'Ничего не найдено'}).waitFor();await p.getByRole('searchbox',{name:'Поиск'}).fill('FX3');await p.getByRole('heading',{name:'Sony FX3'}).waitFor();
await p.getByRole('button',{name:'Редактировать',exact:true}).click();await p.getByLabel('Название',{exact:true}).fill('Sony FX3 II');await p.getByRole('button',{name:'Сохранить',exact:true}).click();await p.locator('dialog').waitFor({state:'hidden'});await p.getByRole('button',{name:'Удалить',exact:true}).click();await p.locator('#confirm-delete').click();await p.locator('dialog').waitFor({state:'hidden'});db=await p.evaluate(()=>JSON.parse(localStorage.getItem('rental-equipment.db')));assert.equal(db.equipment.length,0);
await p.locator('#mobile-nav').getByRole('link',{name:'Клиенты',exact:true}).click();await p.getByRole('button',{name:'Редактировать',exact:true}).click();await p.getByLabel('Имя / название компании').fill('Кадр II');await p.getByRole('button',{name:'Сохранить',exact:true}).click();await p.locator('dialog').waitFor({state:'hidden'});await p.getByRole('button',{name:'Удалить',exact:true}).click();await p.locator('#confirm-delete').click();await p.locator('dialog').waitFor({state:'hidden'});
// Separate context: presentation data never enters the user's database.
const visual=await browser.newContext({viewport:{width:1440,height:1024}});const v=await visual.newPage();v.on('pageerror',e=>errors.push(e.message));await v.goto(url);await v.getByRole('button',{name:'Настройки и резервная копия'}).click();await v.getByRole('button',{name:'Загрузить тестовый пример'}).click();await v.locator('#confirm-delete').click();await v.locator('dialog').waitFor({state:'hidden'});
await v.locator('#toast').waitFor({state:'hidden'});
for(const [width,height,label]of [[1440,1024,'desktop'],[768,1024,'tablet'],[390,844,'iphone'],[320,700,'small-phone']]){await v.setViewportSize({width,height});await v.waitForTimeout(350);await v.screenshot({path:path.join(artifacts,`${label}.png`),fullPage:false});assert.equal(await v.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`${label} horizontal overflow`);}
await v.setViewportSize({width:390,height:844});await v.waitForTimeout(350);await v.locator('.section-title').first().scrollIntoViewIfNeeded();await v.screenshot({path:path.join(artifacts,'equipment-iphone.png')});await v.evaluate(()=>scrollTo(0,0));
for(const target of ['clients','prices','history','statistics']){await v.goto(url+'/#'+target);await v.getByRole('heading',{name:({clients:'Клиенты',prices:'Цены',history:'История',statistics:'Статистика'})[target],exact:true}).waitFor();assert.equal(await v.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,target+' overflow');await v.waitForTimeout(350);await v.screenshot({path:path.join(artifacts,target+'-iphone.png'),fullPage:false});}
await v.goto(url);await v.getByRole('button',{name:'Принять возврат'}).first().click();await v.waitForTimeout(350);await v.screenshot({path:path.join(artifacts,'return-iphone.png'),fullPage:false});await v.getByRole('button',{name:'Закрыть окно'}).click();
// Same tab data persists; another tab receives storage updates.
const second=await visual.newPage();await second.goto(url);await v.getByRole('button',{name:'Добавить оборудование',exact:true}).first().click();await v.getByLabel('Название',{exact:true}).fill('Test sync');await v.getByLabel('Инвентарный номер',{exact:true}).fill('SYNC-1');await v.getByRole('button',{name:'Сохранить',exact:true}).click();await second.getByRole('heading',{name:'Test sync'}).waitFor();
assert.deepEqual(errors,[]);await browser.close();
// WebKit (Safari engine) smoke verification.
let safari;try{safari=await webkit.launch({headless:true});}catch(error){throw Error('WebKit launch failed: '+error.message);}
const sp=await safari.newPage({viewport:{width:390,height:844}});await sp.goto(url);await sp.getByRole('button',{name:'Добавить оборудование',exact:true}).first().click();await sp.getByLabel('Название',{exact:true}).fill('Safari equipment');await sp.getByLabel('Инвентарный номер',{exact:true}).fill('SAF-1');await sp.getByRole('button',{name:'Сохранить',exact:true}).click();await sp.locator('dialog').waitFor({state:'hidden'});await sp.reload();await sp.getByRole('heading',{name:'Safari equipment'}).waitFor();assert.equal(await sp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await safari.close();
console.log('PASS: CRUD, issue/return, 40 000 ₽ calculation, persistence, CSV BOM, backup/restore, search, tariffs, history deletion, tab sync, 4 viewport sizes, Safari WebKit.');
})().catch(async error=>{console.error(error);if(global.debugPage){console.error((await global.debugPage.locator('body').innerText()).slice(0,3500));await global.debugPage.screenshot({path:path.join(artifacts,'failure.png'),fullPage:false});}process.exit(1);});
