const {test}=require('node:test');
const assert=require('node:assert/strict');
const D=require('../assets/domain.js');
function fixture(){const db=D.empty();db.equipment=[{id:'e',name:'Sony FX3',inventory:'CAM-001',rates:[4500,4000,3500,3000],status:'free'}];db.clients=[{id:'c',name:'Клиент',type:'person',documents:[]}];return db;}
const rental={start:'2026-01-01',rates:[4500,4000,3500,3000],bounds:[7,14,21]};
test('one tariff covers the entire term at every boundary',()=>{for(const [days,rate]of [[1,4500],[7,4500],[8,4000],[10,4000],[14,4000],[15,3500],[21,3500],[22,3000],[25,3000],[28,3000]]){assert.deepEqual(D.quote(rental,D.addDays(rental.start,days)),{days,index:rate===4500?0:rate===4000?1:rate===3500?2:3,rate,total:days*rate});}});
test('calendar days handle leap year, same-day and time-zone changes',()=>{assert.equal(D.duration('2024-02-28','2024-03-01'),2);assert.equal(D.duration('2026-01-01','2026-01-01'),1);assert.throws(()=>D.day('2026-02-30'));assert.throws(()=>D.duration('2026-01-02','2026-01-01'));assert.equal(D.duration('2026-03-28','2026-03-30'),2);});
test('fixed rental becomes overdue after due day only',()=>{const db=fixture();const r=D.issue(db,{equipmentId:'e',clientId:'c',start:D.addDays(D.today(),-10),days:7,paid:0});assert.equal(D.status(db,db.equipment[0],r.due),'rented');assert.equal(D.status(db,db.equipment[0],D.addDays(r.due,1)),'overdue');assert.throws(()=>D.removeEquipment(db,'e'));assert.throws(()=>D.removeClient(db,'c'));assert.throws(()=>D.issue(db,{equipmentId:'e',clientId:'c',start:D.today(),days:7}));});
test('open rental has no overdue state and returns at actual cost',()=>{const db=fixture();const r=D.issue(db,{equipmentId:'e',clientId:'c',start:D.addDays(D.today(),-25),days:'open',paid:1000});assert.equal(r.due,null);assert.equal(D.status(db,db.equipment[0]),'rented');db.equipment[0].rates=[1,1,1,1];db.settings.bounds=[1,2,3];D.close(db,r.id,D.today(),1000);assert.equal(r.total,75000);assert.equal(D.balance(db,'c'),74000);assert.equal(D.status(db,db.equipment[0]),'free');assert.equal(D.validate(db),db);db.history=[];assert.equal(D.statistics(db).revenue,75000);D.removeEquipment(db,'e');D.removeClient(db,'c');assert.equal(D.statistics(db).revenue,75000);});
test('repository persists, reloads, rejects quota writes without memory mutation',()=>{let raw=null;const storage={getItem:()=>raw,setItem:(_,v)=>{raw=v;}};let repo=new D.LocalRepository(storage);repo.commit(db=>Object.assign(db,fixture()));repo=new D.LocalRepository(storage);assert.equal(repo.db.equipment.length,1);const saved=raw;storage.setItem=()=>{throw Error('QuotaExceededError')};assert.throws(()=>repo.commit(db=>db.equipment[0].name='Changed'),/Не удалось сохранить/);assert.equal(repo.db.equipment[0].name,'Sony FX3');assert.equal(raw,saved);});
test('stale tab cannot silently overwrite changes',()=>{let raw=null;const storage={getItem:()=>raw,setItem:(_,v)=>{raw=v;}};const a=new D.LocalRepository(storage),b=new D.LocalRepository(storage);a.commit(db=>db.settings.employee='A');assert.throws(()=>b.commit(db=>db.settings.employee='B'),/другой вкладке/);});
test('migration preserves data and rejects newer or corrupt schemas',()=>{const v1=fixture();v1.version=1;delete v1.revision;delete v1.clients[0].documents;const migrated=D.migrate(v1);assert.equal(migrated.version,2);assert.equal(migrated.equipment[0].name,'Sony FX3');assert.deepEqual(migrated.clients[0].documents,[]);assert.throws(()=>D.migrate({...v1,version:99}));assert.throws(()=>D.migrate({version:2}));const raw='{bad';const repo=new D.LocalRepository({getItem:()=>raw,setItem:()=>{throw Error('must not write')}});assert.equal(repo.db,null);assert.ok(repo.error);});
test('CSV has BOM, quoting, line breaks and formula protection',()=>{const value=D.csv([['Имя','Текст'],['=SUM(A1)','Текст; "цитата"\nстрока'],['+7 999','@formula']]);assert.ok(value.startsWith('\ufeff'));assert.ok(value.includes('"\'=SUM(A1)"'));assert.ok(value.includes('"Текст; ""цитата""\nстрока"'));assert.ok(value.includes('\r\n'));});
test('inventory uniqueness and data references are enforced',()=>{const db=fixture();db.equipment.push({...db.equipment[0],id:'e2',inventory:'cam-001'});assert.throws(()=>D.validate(db),/номер/);db.equipment.pop();db.settings.bounds=[7,6,21];assert.throws(()=>D.validate(db),/возрастать/);});
test('period statistics use issue and return dates independently',()=>{const db=fixture(),r=D.issue(db,{equipmentId:'e',clientId:'c',start:D.addDays(D.today(),-10),days:7,paid:0});D.close(db,r.id,D.today(),40000);const s=D.statistics(db,D.today(),D.today());assert.equal(s.rentals,0);assert.equal(s.closed,1);assert.equal(s.revenue,40000);assert.equal(s.received,40000);});
